[package]
name = "aoc-2021"
version = "0.1.0"
authors = ["Jakub DÄ…bek <jakub.dabek@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-utils = { path = '../aoc-utils' }
